# Master配置
spark.master                     spark://spark-master:7077

# Web UI配置 - 解决链接跳转问题
spark.ui.reverseProxy           true
spark.ui.reverseProxyUrl        http://90.91.106.126:8080
spark.ui.proxyRedirectUri       http://90.91.106.126
spark.worker.webui.address      http://90.91.106.126

# 事件日志配置
spark.eventLog.enabled           true
spark.eventLog.dir               file:///opt/spark/logs
spark.history.fs.logDirectory    file:///opt/spark/logs

# 序列化配置
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.kryoserializer.buffer.max  256m

# 内存配置
spark.driver.memory              16g
spark.executor.memory            16g
spark.executor.cores             4

# 动态资源分配
spark.dynamicAllocation.enabled          true
spark.dynamicAllocation.minExecutors     1
spark.dynamicAllocation.maxExecutors     4
spark.dynamicAllocation.initialExecutors 2

# 网络配置
spark.network.timeout            300s
spark.executor.heartbeatInterval 30s
spark.rpc.askTimeout             300s

# Shuffle配置
spark.shuffle.service.enabled    true
spark.shuffle.compress           true

# SQL配置
spark.sql.adaptive.enabled       true

# Python配置
spark.sql.execution.arrow.pyspark.enabled true
# spark.pyspark.python              python3
#spark.pyspark.driver.python       python3

# 日志配置
spark.eventLog.compress          true
